export const apiConfig = {
  // baseURL: import.meta.env.VITE_API_URL_PROD || "https://kingdergarten-api-gmena8b7cug2f4cr.southeastasia-01.azurewebsites.net/api/pms/",
  baseURL: "https://overly-ectodermoidal-brunilda.ngrok-free.dev/api/pms/",
};

export const apiEndPoint = {
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  CURRENT_USER: "/auth/getCurrentUser",
  STUDENT_BY_PARENT: "/dashboard-parent/getStudentByParent",
  SC_BY_CLASS_MONTH: "/dashboard-schedules/getSchedulesByClassAndMonth",
  MENU_BY_AGE_DATE: "/dashboard-menus/getMenuByAgeAndDate",
  CLASS_BY_STU_SY: "/dashboard-class/getClassByStuAndSY",
  ATT_BY_STU_DATE: "/dashboard-attendances/getAttByStuAndDate",
  MED_BY_STUDENT: "/dashboard-medicals/getMedicalByStudent",
  FB_BY_STU_DATE: "/dashboard-feedbacks/getFbByStuAndDate",
  SY_LIST: "/dashboard-class/shoolYear/list",
  CREATE_NEW_POST: "/posts/create",
  UPLOAD_ALBUM: (postId: string) => `/posts/${postId}/upload`,
  GET_CLASS_OF_TEACHER: (teacherId: string) =>
    `/posts/getClassByTeacher/${teacherId}`,
  GET_LIST_POST: (teacherId: string) =>
    `/posts/getPostFileByTeacher/${teacherId}`,
  DELETE_POST: (postId: string) => `/posts/delete/${postId}`,
  DELETE_IMAGE: (imageId: string) => `/post-files/${imageId}/delete`,
  UPDATE_POST: (postId: string) => `/posts/update/${postId}`,
  GET_LIST_POST_BY_STUDENT: (studentId: string) =>
    `/dashboard-posts/getPostFileByStudent/${studentId}`,
  GET_CLASS_AND_STUDENT_BY_TEACHER: (id: string) =>
    `/teachers/getClassByTeacher/${id}`,
  GET_SCHOOLYEARS_LIST: "/schoolYears/list",
  GET_ATTENDANCE_BY_ID: (id: string) => `/attendances/getById/${id}`,
  GET_ATTENDANCE_BY_CLASS_AND_SCHOOLYEAR: (
    classId: string,
    schoolYearId: string
  ) => `/attendances/getByClassAndSchoolYear/${classId}/${schoolYearId}`,
  GET_ATTENDANCE_BY_CLASS_AND_DATE: (id: string, date: string) =>
    `/attendances/getByClassAndDate/${id}/${date}`,
  GET_STUDENT_DETAILS: (id: string) => `/teachers/getByIdStudent/${id}`,
  GET_FEEDBACK_BY_CLASS_AND_DATE: `/feedbacks/getByClassAndDate`,
  GET_FEEDBACK_BY_ID: (id: string) => `/feedbacks/getByIdFeedback/${id}`,
  GET_ATTENDANCE_LIST: "/attendances/list",
  CREATE_ATTENDANCE: "/attendances/create",
  UPDATE_ATTENDANCE: (id: string) => `/attendances/update/${id}`,
  DELETE_ATTENDANCE: (id: string) => `/attendances/delete/${id}`,
  CREATE_FEEDBACK: "/feedbacks/createFeedbacks",
  UPDATE_FEED_BACK: (id: string) => `/feedbacks/update/${id}`,
  DELETE_FEED_BACK: (id: string) => `/feedbacks/delete/${id}`,
  GET_SCHEDULE_BY_ID: (id: string) => `/schedules/getById/${id}`,
  GET_SCHEDULE_PARAMS: "/schedules/getByParams",
  CREATE_SCHEDULE: "/schedules/createSchedule",
  UPDATE_SCHEDULE: (id: string) => `/schedules/updateSchedule/${id}`,
  PREVIEWS_SCHEDULE: "/schedules/previewSchedules",
  GET_PDF_BY_IDS: (id: string) => `/teachers/pdf/${id}`,
  GET_CLASS_LIST: "/classes/list",
  GET_SCHEDULE_WEEK: "/lessons/get-schedule-week",
  GET_LESSON_BY_ID: (id: string) => `/lessons/getById/${id}`,
  CREATE_LESSON: "/lessons/create",
  UPDATE_LESSON: (id: string) => `/lessons/update/${id}`,
  APPROVE_LESSON: (id: string) => `/lessons/approve-request/${id}`,
  REJECT_LESSON: (id: string) => `/lessons/reject-request/${id}`,
  GET_LIST_LESSON: "/lessons/get-list",
  SEND_LESSON: (id: string) => `/lessons/send-request/${id}`,
  GET_TIMETABLE_TEACHER: "/time-table/get-timetable-teacher",
};
