export const apiConfig = {
  // baseURL: import.meta.env.VITE_API_URL_PROD || "https://kingdergarten-api-gmena8b7cug2f4cr.southeastasia-01.azurewebsites.net/api/pms/",
  baseURL: "https://overly-ectodermoidal-brunilda.ngrok-free.dev/api/pms/",
  // baseURL: "http://localhost:9999/api/pms/",
};

export const apiEndPoint = {
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  CURRENT_USER: "/auth/getCurrentUser",
  STUDENT_BY_PARENT: "/dashboard-parent/getStudentByParent",
  SC_BY_CLASS_MONTH: "/dashboard-schedules/getSchedulesByClassAndMonth",
  MENU_BY_AGE_DATE: "/dashboard-menus/getMenuByAgeAndDate",
  CLASS_BY_STU_SY: "/dashboard-class/getClassByStuAndSY",
  ATT_BY_STU_DATE: "/dashboard-attendances/getAttByStuAndDate",
  MED_BY_STUDENT: "/dashboard-medicals/getMedicalByStudent",
  FB_BY_STU_DATE: "/dashboard-feedbacks/getFbByStuAndDate",
  SY_LIST: "/dashboard-class/shoolYear/list",
  CREATE_NEW_POST: "/posts/create",
  UPLOAD_ALBUM: (postId: string) => `/posts/${postId}/upload`,
  GET_CLASS_OF_TEACHER: (teacherId: string) =>
    `/posts/getClassByTeacher/${teacherId}`,
  GET_LIST_POST: (teacherId: string) =>
    `/posts/getPostFileByTeacher/${teacherId}`,
  DELETE_POST: (postId: string) => `/posts/delete/${postId}`,
  DELETE_IMAGE: (imageId: string) => `/post-files/${imageId}/delete`,
  UPDATE_POST: (postId: string) => `/posts/update/${postId}`,
  GET_LIST_POST_BY_STUDENT: (studentId: string) =>
    `/dashboard-posts/getPostFileByStudent/${studentId}`,
  GET_CLASS_AND_STUDENT_BY_TEACHER: (id: string) =>
    `/teachers/getClassByTeacher/${id}`,
  GET_SCHOOLYEARS_LIST: "/schoolYears/list",
  SEND_LESSON: (id: string) => `/lessons/send-request/${id}`,
  APPROVE_LESSON: (id: string) => `/lessons/approve-request/${id}`,
  REJECT_LESSON: (id: string) => `/lessons/reject-request/${id}`,
  GET_TIMETABLE_TEACHER: "/time-table/get-timetable-teacher",
  UPDATE_LESSON: (id: string) => `/lessons/update/${id}`,
  CREATE_LESSON: "/lessons/create",
  GET_LESSON_BY_ID: (id: string) => `/lessons/getById/${id}`,
  GET_SCHEDULE_WEEK: "/lessons/get-schedule-week",
  GET_LIST_LESSON: "/lessons/get-list",
  DELETE_FEED_BACK: (id: string) => `/feedbacks/delete/${id}`,
  GET_ENROLLMENT_BY_ID: (id: string) => `/enrollments/getById/${id}`,
  UPLOAD_PDF: "/enrollments/uploadPDF",
  GET_PDF_BY_ID: (id: string) => `/enrollments/pdf/${id}`,
  GET_PDF_BY_IDS: (id: string) => `/teachers/pdf/${id}`,
  APPROVE_ENROLLMENT: "/enrollments/aprrovedEnroll",
  UPDATE_ENROLLMENT: (id: string) => `/enrollments/update/${id}`,
  REJECT_ENROLLMENT: (id: string) => `/enrollments/rejectEnroll/${id}`,
  APPROVE_ALL_ENROLLMENT: "/enrollments/approvedEnrollAll",
  GET_LIST_MENU: "/menus/list",
  CREATE_MENU: "/menus/create",
  DELETE_MENU: (menuId: string) => `/menus/delete/${menuId}`,
  GET_MENU_BY_ID: (menuId: string) => `/menus/get-by-id/${menuId}`,
  CREATE_SCHOOLYEAR: "/schoolYears/create",
  GET_LIST_FOOD: "/foods/list",
  CREATE_FOOD: "/foods/create",
  UPDATE_FOOD: (id: string) => `/foods/update/${id}`,
  DELETE_FOOD: (id: string) => `/foods/delete/${id}`,
  CALCULATE_FOOD_AI: (foodId: string) => `foods/caculate-calo/${foodId}`,
  CALCULATE_TOTAL_CALO_AI: `foods/caculate-calo`,
  UPDATE_SCHOOLYEAR: (id: string) => `/schoolYears/update/${id}`,
  DELETE_SCHOOLYEAR: (id: string) => `/schoolYears/delete/${id}`,
  CONFIRM_SCHOOLYEAR: (id: string) => `/schoolYears/confirm/${id}`,
  GET_SCHOOLYEAR_BY_ID: (id: string) => `/schoolYears/getById/${id}`,
  END_SCHOOLYEAR: (id: string) => `/schoolYears/endSchoolYear/${id}`,
  SCHOOLYEAR_REPORT: "/schoolYears/getStudentGraduated",
  EDIT_MENU: (menuId: string) => `/menus/update/${menuId}`,
  APPROVE_MENU: (menuId: string) => `/menus/approve-menu/${menuId}`,
  REJECT_MENU: (menuId: string) => `/menus/reject-menu/${menuId}`,
  GET_CLASS_LIST: "/classes/list",
  GET_CLASS_BY_ID: (id: string) => `/classes/getById/${id}`,
  UPDATE_CLASS: (id: string) => `/classes/update/${id}`,
  CREATE_CLASS: "/classes/create",
  GET_AVAILABEL_STUDENT: "/classes/available-student",
  GET_AVAILABEL_TEACHER: "/classes/available-teacher",
  GET_AVAILABEL_ROOM: "/classes/available-room",
  ASYNC_CLASS: "/classes/async-class",
  GET_AVAILABEL_CLASS_STUDENT: "/classes/available-classStudent",
  GET_AVAILABEL_CLASS_TEACHER: "/classes/available-classTeacher",
  STUDENT_CHANGE_CLASS: "/classes/studentChangeClass",
  TEACHER_CHANGE_CLASS: "/classes/teacherChangeClass",
  GET_CURRICULUMS_LIST: "/curriculums/list",
  GET_CURRICULUMS_BY_ID: (id: string) => `/curriculums/getById/${id}`,
  CREATE_CURRICULUMS: "/curriculums/create",
  UPDATE_CURRICULUMS: (id: string) => `/curriculums/update/${id}`,
  DELETE_CURRICULUMS: (id: string) => `/curriculums/delete/${id}`,
  GET_EVENT_LIST: "/events/list/",
  GET_EVENT_BY_ID: (id: string) => `/events/getById/${id}`,
  CREATE_EVENT: "/events/create",
  UPDATE_EVENT: (id: string) => `/events/update/${id}`,
  DELETE_EVENT: (id: string) => `/events/delete/${id}`,
  GET_LIST_ROOM: "/rooms/list",
  CREATE_ROOM: "/rooms/create",
  UPDATE_ROOM: (id: string) => `/rooms/update/${id}`,
  DELETE_ROOM: (id: string) => `/rooms/delete/${id}`,
  GET_ROOM_BY_ID: (id: string) => `/rooms/getById/${id}`,
  GET_TOPIC_LIST: "/topics/list",
  GET_TOPIC_BY_ID: (id: string) => `/topics/getById/${id}`,
  GET_AVAILABEL_TOPIC: `/topics/getAvailable`,
  CREATE_TOPIC: "/topics/create",
  UPDATE_TOPIC: (id: string) => `/topics/update/${id}`,
  DELETE_TOPIC: (id: string) => `/topics/delete/${id}`,
  GET_ATTENDANCE_LIST: "/attendances/list",
  CREATE_ATTENDANCE: "/attendances/create",
  UPDATE_ATTENDANCE: (id: string) => `/attendances/update/${id}`,
  DELETE_ATTENDANCE: (id: string) => `/attendances/delete/${id}`,
  GET_ATTENDANCE_BY_ID: (id: string) => `/attendances/getById/${id}`,
  GET_TEACHER_INFO: (id: string) => `/accounts/getInforTeacher/${id}`,
  UPDATE_TEACHER_INFO: (id: string) => `/accounts/updateInforTeacher/${id}`,
  CHANGE_PASS_TEACHER: (id: string) => `/accounts/changePasswordTeacher/${id}`,

  GET_ATTENDANCE_BY_CLASS_AND_SCHOOLYEAR: (
    classId: string,
    schoolYearId: string
  ) => `/attendances/getByClassAndSchoolYear/${classId}/${schoolYearId}`,
  GET_ATTENDANCE_BY_CLASS_AND_DATE: (id: string, date: string) =>
    `/attendances/getByClassAndDate/${id}/${date}`,
  GET_STUDENT_DETAILS: (id: string) => `/teachers/getByIdStudent/${id}`,
  GET_FEEDBACK_BY_CLASS_AND_DATE: `/feedbacks/getByClassAndDate`,
  GET_FEEDBACK_BY_ID: (id: string) => `/feedbacks/getByIdFeedback/${id}`,
  CREATE_FEEDBACK: "/feedbacks/createFeedbacks",
  UPDATE_FEED_BACK: (id: string) => `/feedbacks/update/${id}`,
  GET_SCHEDULE_BY_ID: (id: string) => `/schedules/getById/${id}`,
  GET_SCHEDULE_PARAMS: "/schedules/getByParams",
  CREATE_SCHEDULE: "/schedules/createSchedule",
  UPDATE_SCHEDULE: (id: string) => `/schedules/updateSchedule/${id}`,
  PREVIEWS_SCHEDULE: "/schedules/previewSchedules",
  GET_FIX_ACTIVITY: "/schedules/getFixActivity",
  GET_AVAILABEL_ACTIVITY: "/schedules/getListAvailable",
  CONFIRM_SCHEDULE: (id: string) => `/schedules/confirm/${id}`,
  GET_CLASS_BY_SCHOOLYEAR: "/schedules/getClassBySchoolYear",
  GET_LIST_REVENUES: "/revenues/list",
  GET_REVENUES_BY_ID: (id: string) => `/revenues/getById/${id}`,
  CREATE_REVENUES: "/revenues/create",
  UPDATE_REVENUES: (id: string) => `/revenues/update/${id}`,
  DELETE_REVENUES: (id: string) => `/revenues/delete/${id}`,
  GET_SCHOOLYEAR: "/services/school-year-list",
  GET_PREVIEW_SERVICES: "/services/preview",
  GET_SERVICES_BY_ID: () => "/services/getById",
  CREATE_SERVICES: "/services/create",
  UPDATE_SERVICES: (id: string) => `/services/update/${id}`,
  GET_RECEIPT_LIST: "/receipts/list",
  GET_RECEIPT_BY_ID: (id: string) => `/receipts/getById/${id}`,
  CREATE_RECEIPT: "/receipts/create",
  UPDATE_RECEIPT: (id: string) => `/receipts/update/${id}`,
  DELETE_RECEIPT: (id: string) => `/receipts/delete/${id}`,
  GET_REVENUES_RECEIPT: "/receipts/getRevenue",
  CONFIRM_RECEIPT: (id: string) => `/receipts/confirm/${id}`,
  GET_TUITION_LIST: "/tuition-manage/list",
  GET_DETAILS_TUITION: (parentid: string) => `/tuitions/detail/${parentid}`,
  CONFIRM_TUITION: "/tuitions/confirm/",
  CHECK_STATUS_TUITION: (orderCode: string) =>
    `/tuitions/check-status/${orderCode}`,
  GET_LIST_HISTORY_FEE: "/tuitions/historyFees",
  GET_DETAIL_BALANCES: "/balances/detail",
  GET_LIST_DOCUMENT: "/documents/list",
  GET_DOCUMENT_BY_ID: (id: string) => `/documents/getById/${id}`,
  CREATE_DOCUMENT: "/documents/create",
  UPDATE_DOCUMENT: (id: string) => `/documents/update/${id}`,
  DELETE_DOCUMENT: (id: string) => `/documents/delete/${id}`,
  CONFIRM_DOCUMENT: (id: string) => `/documents/confirmPayment/${id}`,
  GET_REPORT_SERVICES: "/manage-services/reports",
  PAYMENT_ENROLLMENT_CONFIRM: (id: string) =>
    `/enrollments/payment-enroll/${id}`,
  UPLOAD_IMAGE: "/enrollments/uploadImage",
  GET_LIST_MEDICAL: "/medicals/list",
  GET_MEDICAL_BY_ID: (id: string) => `/medicals/getById/${id}`,
  CREATE_MEDICAL: "/medicals/create",
  UPDATE_MEDICAL: (id: string) => `/medicals/update/${id}`,
  DELETE_MEDICAL: (id: string) => `/medicals/delete/${id}`,
  GET_LIST_PARENT_STUDENT: (id: string) =>
    `/dashboard-parent/getStudentByParent/${id}`,
  GET_INFOR_PARENT: (id: string) =>
    `/dashboard-parent/getInforParent/${id}`,
  CHANGE_PASS_PARENT: (id: string) =>
    `/dashboard-parent/changePassParent/${id}`,
  UPDATE_INFOR_PARENT: (id: string) =>
    `/dashboard-parent/updateParent/${id}`,
  GET_POST_BY_STUDENT: (id: string) =>
    `/dashboard-posts/getPostFileByStudent/${id}`,
  GET_DASHBOARD_SCHEDULE: "/dashboard-schedules/getSchedulesByClassAndMonth",
  GET_DASHBOARD_CLASS: "/dashboard-class/getClassByStuAndSY",
  GET_LIST_FEEDBACK: "/dashboard-feedbacks/getFbByStuAndDate",
  GET_LIST_MEDICAL_CHILD: (id: string) =>
    `/dashboard-medicals/getMedicalByStudent/${id}`,
  GET_LIST_CHILD: (parentId: string) =>
    `/dashboard-parent/getStudentByParent/${parentId}`,
  GET_DATA_CHECK_IN: "/dashboard-attendances/getAttByStuAndDate",
  GET_DATA_CLASS: "/dashboard-class/getClassByStuAndSY",
  GET_DATA_SCHEDULE: "/dashboard-schedules/getSchedulesByClassAndMonth",
  GET_DATA_MENU_CHILD: "/dashboard-menus/getMenuByAgeAndDate",
  GET_SCHOOL_YEAR_PARENT: "/dashboard-class/shoolYear/list",
  GET_PDF_BY_PARENTS: (id: string) => `/dashboard-medicals/pdf/${id}`,
  CREATE_GUARDIAN: "/guardians/create",
  UPDATE_GUARDIAN: (id: string) => `/guardians/update/${id}`,
  DELETE_GUARDIAN: (id: string) => `/guardians/delete/${id}`,
  GET_GUARDIAN_BY_ID: (id: string) => `/guardians/getById/${id}`,
  GET_LIST_GUARDIAN_BY_STUDENT: (studentId: string) =>
    `/guardians/listByStudent/${studentId}`,
  GET_LIST_GUARDIAN_BY_PARENT: (parentId: string) =>
    `/guardians/listByParent/${parentId}`,
  GET_TUITION_BY_PARENT: (parentId: string) =>
    `/tuitions/detail/${parentId}`,
};
